Direct Messages Step 4 updates
ArgaAlan/CodeU-2019 pull request #11
Opened 2019-02-23 21:02 UTC by gjchong25

2019-02-25 18:01 UTC, acolwell requested changes
Your code changes seem pretty good. In general, I'd suggest separating comments that help you personally understand the code vs comments that make a complicated part of the code clearer in general. I sometimes keep a document/notepad with reminders about the code if there is something I need to remember, but isn't necessarily confusing for others.

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/data/Datastore.java
> +    //messages stored in an arraylist
Remove? This isn't really adding any extra info.

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/data/Datastore.java
> +        String recipient = (String) entity.getProperty("recipient");
nit: Move below timestamp so it mirrors the code in storeMessage(). I know this doesn't functionally change the code, but it makes it easier to compare the 2 functions and verify they are getting/setting all the same properties.

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/data/Message.java
>    private String user;
Maybe add an  '// author of message' comment here to complement the recipient comment below?

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/LoginServlet.java
> +//responds to any request made at /login
Remove or add to JavaDoc comment above if you feel it makes things clearer.

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +
Please remove

2019-02-25 18:01 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    String recipient = request.getParameter("recipient");
It seems like some validation code should be added here to protect against invalid recipients.

2019-02-25 18:01 UTC, acolwell commented on src/main/webapp/js/user-page-loader.js
> +*/
Please merge into the comment in the line above if you still want to keep this comment.

2019-02-25 18:01 UTC, acolwell commented on src/main/webapp/user-page.html
> +    <!-- doGet() fires when user requests /messages URL-->
Remove and/or put these in the servelet code instead. My main reasoning is that these comments reveal details of the implementation in user visible parts of the HTML. I know this isn't a super secret or secure app but I though it might be good to raise this issue so you can be aware of it.

2019-03-01 16:42 UTC, gjchong25 commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    String recipient = request.getParameter("recipient");
Would invalid recipients in this case be null or empty strings?

2019-03-03 20:00 UTC, acolwell requested changes

2019-03-03 20:00 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    String recipient = request.getParameter("recipient");
So I think null is probably ok, because I think that is equivalent to the non-DM case that the code already has. I was mainly thinking about using the userService to verify that recipients actually refer to a real user. Right now it looks like any string can be passed in and I think you probably want to restrict this code to only accept strings that refer to actual users.

2019-03-04 17:02 UTC, acolwell requested changes
Looks good, but I believe you still need to merge in changes from master and resolve the conflicts. I'm happy to help you do this.

2019-03-04 17:02 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +
nit: Please remove these empty lines.

2019-03-04 17:02 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    }
nit: Please remove trailing space.

2019-03-04 17:02 UTC, acolwell commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    String recipient = request.getParameter("recipient");
Sorry I misspoke here. I actually meant check the DataStore and not the userService.
I was thinking of something like the following to handle errors:

if (recipient == null || datastore.getUser(recipient) == null) {
    response.sendRedirect("/user-page.html?user=" + user);
    return;
}

After looking at the direct message Familiarization Project page again I realized that you are actually being asked to change the behavior to only allow direct messages, so I take back my comment about saying recipient is ok to be null. Again, I'm sorry about sending conflicting signals.

2019-03-04 22:56 UTC, acolwell approved these changes
LGTM

2019-03-05 16:37 UTC, merged